
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nsevent'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  VW_NEWSTORE:
    # Config indicated by + and applies to all files under models/example/
    +schema: nsevent_raw
    +materialized: table # for building the package, switch to views later? 

vars:
  connector:
    table_name: "{{ ref('stg_connector__table_name') }}" # all references to staging models should be vars

  connector_source:
    table_name: "{{ source('connector', 'table_name') }}" # all sources should be va