{{ config(materialized='view') }}

WITH 

UNION_TRAFFIC AS (

SELECT *
FROM {{ ref("T_RAW_TRAFFIC") }}

UNION ALL

SELECT *
FROM {{ ref("V_RAW_H_TRAFFIC") }}

),

CONVERSION_TRAFFIC AS (

SELECT
CD.[FISCAL YEAR] AS FISCAL_YEAR
,CD.[FISCAL PERIOD] AS FISCAL_PERIOD
,CD.[FISCAL WEEK] AS FISCAL_WEEK
,UNION_TRAFFIC.[DATE]
--,RAW_BRANCH
,UNION_TRAFFIC.BRANCH
,BB.BRAND
,BC.CURRENCY
,UNION_TRAFFIC.TRAFFIC

 

FROM UNION_TRAFFIC
 

LEFT JOIN {{ source('m3', 'Z_PBI_CALENDAR_DATA') }} AS CD WITH (NOLOCK)
ON CD.[DATE] COLLATE SQL_Latin1_General_CP1_CI_AS = UNION_TRAFFIC.[DATE] 

 

LEFT JOIN {{ source('m3', 'Z_PBI_BRANCH_BRAND') }} AS BB WITH (NOLOCK)
ON BB.[BRANCH] COLLATE SQL_Latin1_General_CP1_CI_AS = UNION_TRAFFIC.BRANCH 

 

LEFT JOIN {{ source('m3', 'Z_PBI_BRANCH_CURRENCY') }} AS BC WITH (NOLOCK)
ON BC.[BRANCH] COLLATE SQL_Latin1_General_CP1_CI_AS  = UNION_TRAFFIC.BRANCH

)

SELECT
CONCAT(BRANCH,'-',CURRENCY,'-',BRAND,'-',[DATE] COLLATE SQL_Latin1_General_CP1_CI_AS) AS ID
,FISCAL_YEAR
,FISCAL_PERIOD
,FISCAL_WEEK
,[DATE]
,BRANCH
,BRAND
,CURRENCY
,SUM(TRAFFIC) AS TRAFFIC 

FROM
CONVERSION_TRAFFIC

GROUP BY
FISCAL_YEAR
,FISCAL_PERIOD
,FISCAL_WEEK
,[DATE]
,BRANCH
,BRAND
,CURRENCY