{{ config(materialized='table') }}

GA_UNION AS (

SELECT *
FROM GA3

UNION ALL
SELECT *
FROM GA4

),

GA AS (

SELECT
 CONCAT(GA_UNION.BRANCH,'-',GA_UNION.CURRENCY,'-',GA_UNION.[BRAND],'-',GA_UNION.[date]) AS ID
,CAL.[FISCAL_YEAR] AS [FISCAL_YEAR]
,CAL.[FISCAL_PERIOD] AS [FISCAL_PERIOD]
,CAL.[FISCAL_WEEK] AS [FISCAL_WEEK]
,GA_UNION.[date] AS [DATE]
,GA_UNION.BRANCH
,GA_UNION.[BRAND]
,GA_UNION.CURRENCY 
,GA_UNION.[traffic] AS TRAFFIC
,TRAFFIC_TYPE = 'E-COM'

FROM GA_UNION

LEFT JOIN [M3RPTDEV].[dbo].[Z_PBI_CALENDAR_DATA] AS CAL ON
CAL.[DATE] = GA_UNION.[date]