{{ config(materialized='table') }}

with 

final as (

--OPEN_ORDERS AS (

SELECT
 OD.WHLO AS WAREHOUSE
,MM.BUAR AS BRAND
,CASE LEFT(OD.FACI,2)
	WHEN 'CA' THEN 'CA'
	WHEN 'EU' THEN 'EU'
	WHEN 'GB' THEN 'UK'
	WHEN 'US' THEN 'US'
	WHEN 'DE' THEN 'EU'
	WHEN 'FR' THEN 'EU'
	WHEN 'NL' THEN 'EU'
		ELSE 'MISSING REGION'
			END AS REGION
,LEFT(OD.FACI,2) AS COUNTRY
,OH.ORDT AS TRANSACTION_DATE
,DATEDIFF(DAY,CONVERT(VARCHAR, OH.ORDT,23),CONVERT(VARCHAR, GETDATE(),23)) AS [DELAY]
,OD.CUOR AS PO
,OD.ORNO AS M3_PO
,OH.CUNO AS CUSTOMER 
,OD.PONR AS LINE_NB
,OD.ITNO AS SKU
,MP.POPN AS UPC
,OD.ORST AS LINE_STATUS
,CASE OD.ORST 
	WHEN '05' THEN 'Quotation'
	WHEN '10' THEN 'Preliminary'
	WHEN '22' THEN 'Reserved'
	WHEN '33' THEN 'Allocated'
	WHEN '44' THEN 'Picking List Printed'
	WHEN '66' THEN 'Delivered'
	WHEN '77' THEN 'Invoiced'
	WHEN '99' THEN 'Completed'
		ELSE 'N/A'
			END AS LINE_STATUS_DESCRIPTION

,OD.ORQT AS ORDER_QUANTITY
,OD.RNQT + OD.ALQT + OD.PLQT AS REMAINING_QTY
,OD.ALQT AS ALLOCATED_QTY
,OD.PLQT AS PICK_QTY

,OH.CUCD AS CURRENCY
,OD.ORQT*OD.SAPR AS LOCAL_AMOUNT

,CASE WHEN CURRENCY.RATE IS NOT NULL THEN CURRENCY.RATE ELSE 1 END AS RATE
,OD.ORQT*OD.SAPR*CURRENCY.RATE AS CAD_AMOUNT

FROM [M3RPTDEV].[dbo].[OOLINE] AS OD

LEFT JOIN [M3RPTDEV].[dbo].OOHEAD AS OH
ON  OH.ORNO = OD.ORNO
AND OH.CUNO = OD.CUNO
AND OH.CONO = '100'
AND OH.DELETED = 'N'

-- CALENDAR --
LEFT JOIN [M3RPTDEV].[dbo].CSYPER AS FP
ON FP.DIVI = 'CAN'  
AND FP.PETP = '1' 
AND (OH.ORDT BETWEEN FP.FDAT AND FP.TDAT)

LEFT JOIN [M3RPTDEV].[dbo].CSYPER AS FW
ON FW.DIVI = 'CAN'  
AND FW.PETP = '9' 
AND (OH.ORDT BETWEEN FW.FDAT AND FW.TDAT)

LEFT JOIN [M3RPTDEV].[dbo].MITPOP AS MP
ON MP.ITNO = OD.ITNO
AND MP.ALWQ = 'UPC'
AND MP.DELETED = 'N'

LEFT JOIN [M3RPTDEV].[dbo].OCUSMA AS CUST
ON CUST.CUNO = OH.CUNO
AND CUST.DELETED = 'N'

LEFT JOIN [M3RPTDEV].[dbo].MITMAS AS MM
ON MM.ITNO = OD.ITNO
AND MM.CONO = '100'
AND MM.deleted = 'N'

LEFT JOIN CURRENCY
ON CURRENCY.CURRENCY = OH.CUCD
AND OH.ORDT BETWEEN CURRENCY.FROM_DATE AND CURRENCY.TO_DATE

WHERE 
OH.ORTP IN ('EC1','EC2')
AND OH.CONO = '100'
AND OH.DELETED = 'N'
AND MM.ITTY IN ('M01','M06')
AND OD.ORST <> '99'
AND OD.ORST <> '77'
AND OD.ORST <> '66'

),

OPEN_ORDERS_TABLE AS (

SELECT
 REGION
,CASE COUNTRY
	WHEN 'GB' THEN 'UK'
		ELSE COUNTRY
			END AS COUNTRY
,WAREHOUSE
,BRAND
,CONVERT(VARCHAR, TRANSACTION_DATE,23) AS TRANSACTION_DATE
,[DELAY]
,PO
,M3_PO
,CUSTOMER 
,LINE_NB
,REPLACE(SKU, '/', '_') AS SKU
,UPC
,LINE_STATUS
,LINE_STATUS_DESCRIPTION
,ORDER_QUANTITY
,REMAINING_QTY
,CASE WHEN [DELAY] > 2 THEN ORDER_QUANTITY ELSE 0 END AS ORDER_QUANTITY_DELAY
,CASE WHEN [DELAY] > 2 THEN REMAINING_QTY ELSE 0 END AS REMAINING_QTY_DELAY

,ALLOCATED_QTY
,PICK_QTY

,CURRENCY
,LOCAL_AMOUNT
,CASE WHEN [DELAY] > 2 THEN LOCAL_AMOUNT ELSE 0 END AS LOCAL_AMOUNT_DELAY

,RATE
,CAD_AMOUNT
,CASE WHEN [DELAY] > 2 THEN CAD_AMOUNT ELSE 0 END AS CAD_AMOUNT_DELAY

FROM OPEN_ORDERS

)

SELECT
 CONCAT(REGION,'-',BRAND,'-',PO,'-',SKU) AS ID_M3_ID_PO_SKU
,REGION
,COUNTRY
,CASE
	WHEN REGION = 'CA' THEN 'C31'
	WHEN REGION = 'US' THEN 'U31'
	WHEN REGION = 'EU' THEN 'N31'
	WHEN REGION = 'UK' THEN 'N31'
		END AS MASTER_WAREHOUSE
,MAX(WAREHOUSE) AS WAREHOUSE
,BRAND
,MAX(TRANSACTION_DATE) AS [DATE]
,PO
,CUSTOMER 
,SKU
,UPC
,SUM(ORDER_QUANTITY) AS ORDER_QUANTITY
,SUM(REMAINING_QTY) AS REMAINING_QTY
,SUM(ORDER_QUANTITY_DELAY) AS ORDER_QUANTITY_DELAY
,SUM(REMAINING_QTY_DELAY) AS REMAINING_QTY_DELAY
,SUM(ALLOCATED_QTY) AS ALLOCATED_QTY
,SUM(PICK_QTY) AS PICK_QTY
,CURRENCY
,SUM(LOCAL_AMOUNT) AS LOCAL_AMOUNT
,SUM(LOCAL_AMOUNT_DELAY) AS LOCAL_AMOUNT_DELAY
,RATE
,SUM(CAD_AMOUNT) AS CAD_AMOUNT
,SUM(CAD_AMOUNT_DELAY) AS CAD_AMOUNT_DELAY

FROM OPEN_ORDERS_TABLE

WHERE WAREHOUSE IN ('C31','C32','C01','C02','U31','U01','U02','N31','N01','N02','N08','N38')
AND PO NOT IN ('SKC29288','SKC24687')

GROUP BY
 REGION
,COUNTRY
,BRAND
,PO
,CUSTOMER 
,SKU
,UPC
,CURRENCY
,RATE

  )

select * from final