SELECT [ID_Channel]
      ,[ID_Collection]
      ,[Division]
      ,[Country]
      ,[Store]
      ,[Currency]
      ,[Brand]
      ,[Store_Desc]
      ,[Store_Name_Full_Desc]
      ,[Collection]
      ,[FOH_Capacity_Units]
      ,[BOH_Capacity_Units]
      ,[Off_Site_Capacity_Units]
      ,[Rolling_Racks_Capacity]
      ,[Total_Capacity_Units]
  FROM [M3RPTDEV].[dbo].[Z_PBI_ALLOCATION]