{{ config(materialized='table') }}

with 

final as (

SELECT *
FROM ORDER_HEADER_CA_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_HEADER_CA_SK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_HEADER_US_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_HEADER_US_SK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_HEADER_EU_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_HEADER_UK_MCK WITH (NOLOCK)

)

SELECT
 CAL.F_YEAR AS FISCAL_YEAR
,CAL.F_PERIOD AS FISCAL_PERIOD		
,CAL.F_WEEK AS FISCAL_WEEK
,CAL.F_MONTH AS FISCAL_MONTH
,CONCAT(BRANCH,'-',SHOPIFY_UNION.CURRENCY,'-',BRAND) AS ID_CHANNEL
,CONCAT(REGION,'-',BRAND,'-',ID) AS ID_TABLE
,CONCAT(CREATED_AT,'-',SHOPIFY_UNION.CURRENCY) AS ID_CURRENCY
,CASE WHEN CANCELLED_AT = '' THEN 'NO' ELSE 'YES' END AS CANCELLED_Y_N
,CASE WHEN NEWSTORE_FAILED_TAG = '' THEN 'NO' ELSE 'YES' END AS NEWSTORE_FAILED_Y_N
,CASE WHEN PRE_ORDER_TAG = '' THEN 'NO' ELSE 'YES' END AS PRE_ORDER_Y_N
,CASE WHEN RISKIFIED_DECLINED_TAG = '' THEN 'NO' ELSE 'YES' END AS RISKIFIED_DECLINED_Y_N
,CASE WHEN SFCC_TAG = '' THEN 'NO' ELSE 'YES' END AS SFCC_Y_N
,REGION
,BRAND
,BRANCH
,ID
,PO
,PRE_ORDER_TAG
,NEWSTORE_FAILED_TAG
,RISKIFIED_DECLINED_TAG
,SFCC_TAG
,DISCOUNT_CODE
,DISCOUNT_TYPE
,ORDER_DISCOUNT_AMOUNT
,SHOPIFY_UNION.CURRENCY
,RATE_CAD.RATE
,FINANCIAL_STATUS
,FULFILLMENT_STATUS
,PROCESSED_AT_FULL
,PROCESSED_AT
,CREATED_AT_FULL
,CREATED_AT
,CANCELLED_AT_FULL
,CANCELLED_AT
,CANCEL_REASON
,CLOSED_AT_FULL
,CLOSED_AT
,EMAIL
,NOTE
,SHIPPING_ADDRESS_NAME
,SHIPPING_FIRST_NAME
,SHIPPING_LAST_NAME
,SHIPPING_COMPANY
,SHIPPING_PHONE
,SHIPPING_ADDRESS_1
,SHIPPING_ADDRESS_2
,SHIPPING_CITY
,SHIPPING_ZIP_CODE
,SHIPPING_PROVINCE
,SHIPPING_PROVINCE_CODE
,SHIPPING_COUNTRY
,SHIPPING_COUNTRY_CODE
,BILLING_ADDRESS_NAME
,BILLING_FIRST_NAME
,BILLING_LAST_NAME
,BILLING_COMPANY
,BILLING_PHONE
,BILLING_ADDRESS_1
,BILLING_ADDRESS_2
,BILLING_CITY
,BILLING_ZIP_CODE
,BILLING_PROVINCE
,BILLING_PROVINCE_CODE
,BILLING_COUNTRY
,BILLING_COUNTRY_CODE

FROM SHOPIFY_UNION WITH (NOLOCK)

LEFT JOIN CAL WITH (NOLOCK)
ON CAL.[DATE] = SHOPIFY_UNION.CREATED_AT

LEFT JOIN #RATE AS RATE_CAD WITH (NOLOCK)
ON RATE_CAD.CURRENCY COLLATE SQL_Latin1_General_CP1_CI_AS = SHOPIFY_UNION.CURRENCY COLLATE SQL_Latin1_General_CP1_CI_AS
AND REPLACE(CREATED_AT, '-','') BETWEEN RATE_CAD.FROM_DATE AND RATE_CAD.TO_DATE
AND RATE_CAD.RATE_TYPE = 'CONVERT TO CAD'