{{ config(materialized='table') }}

with 

final as (

SELECT *
FROM OL_CA_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM OL_CA_SK WITH (NOLOCK)

UNION ALL
SELECT *
FROM OL_US_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM OL_US_SK WITH (NOLOCK)

UNION ALL
SELECT *
FROM OL_EU_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM OL_UK_MCK WITH (NOLOCK)

)

SELECT
 CAL.F_YEAR AS FISCAL_YEAR
,YEAR(CREATED_AT) AS ISO_YEAR
,CAL.F_PERIOD AS FISCAL_PERIOD
,MONTH(CREATED_AT) AS ISO_MONTH
,CAL.F_WEEK AS FISCAL_WEEK
,CAL.F_MONTH AS FISCAL_MONTH
,CASE WHEN CANCELLED_AT = '' THEN 'NO' ELSE 'YES' END AS CANCELLED_Y_N
,CASE WHEN NEWSTORE_FAILED_TAG = '' THEN 'NO' ELSE 'YES' END AS NEWSTORE_FAILED_Y_N
,CASE WHEN PRE_ORDER_TAG = '' THEN 'NO' ELSE 'YES' END AS PRE_ORDER_Y_N
,CASE WHEN RISKIFIED_DECLINED_TAG = '' THEN 'NO' ELSE 'YES' END AS RISKIFIED_DECLINED_Y_N
,CASE WHEN SFCC_TAG = '' THEN 'NO' ELSE 'YES' END AS TAGS_SFCC_Y_N
,CONCAT(REGION,'-',BRAND,'-',order_id) AS ID_TABLE
,CONCAT(REGION,'-',BRAND) AS ID_RG_BRAND
,CONCAT(REGION,'-',BRAND,'-',order_id,'-',id) AS ID_SP_FULFILLMENT
,CONCAT(REGION,'-',BRAND,'-',PO,'-',SKU) AS ID_M3_ID_PO_SKU
,CONCAT(BRANCH,'-',SHOPIFY_UNION.CURRENCY,'-',BRAND) AS ID_CHANNEL
,REGION
,BRAND
,BRANCH
,order_id
,id
,product_id
,variant_id
,PO
,PRE_ORDER_TAG
,NEWSTORE_FAILED_TAG
,RISKIFIED_DECLINED_TAG
,SFCC_TAG
,DATEDIFF(DAY,CREATED_AT,GETDATE()) AS [DELAY]
,CASE WHEN DATEDIFF(DAY,CREATED_AT,GETDATE()) > 2 THEN 'URGENT' ELSE 'TO PACK' END AS [PRIORITY]
,SHOPIFY_UNION.CURRENCY
,RATE_CAD.RATE
,FINANCIAL_STATUS
,ORDER_STATUS
,CASE WHEN ORDER_STATUS = '' THEN 'NO' ELSE 'YES' END AS FULFILLED_ORDER_LEVEL_Y_N
,PROCESSED_AT_FULL
,PROCESSED_AT
,CREATED_AT_FULL
,CREATED_AT
,CANCELLED_AT_FULL
,CANCELLED_AT
,CANCEL_REASON
,CLOSED_AT_FULL
,CLOSED_AT
,EMAIL
,NOTE
,BRAND_ITEM
,STYLE
,VARIANT
,FULL_NAME
,SKU
,PRICE
,TOTAL_DISCOUNT
,QTY
,SUBTOTAL
,QTY_ADJ
,CASE WHEN DATEDIFF(DAY,CREATED_AT,GETDATE()) > 2 THEN QTY_ADJ ELSE 0 END AS LATE_QTY
,SUBTOTAL_ADJ
,[PRICE]*[QTY_ADJ] AS GROSS_DEMAND
,CASE WHEN DATEDIFF(DAY,CREATED_AT,GETDATE()) > 2 THEN QTY_ADJ*PRICE ELSE 0 END AS GROSS_DEMAND_LATE
,[PRICE]*[QTY_ADJ]*RATE_CAD.RATE AS GROSS_DEMAND_CAD
,CASE WHEN DATEDIFF(DAY,CREATED_AT,GETDATE()) > 2 THEN QTY_ADJ*PRICE*RATE_CAD.RATE ELSE 0 END AS GROSS_DEMAND_CAD_LATE
,CASE WHEN FULFILLMENT_STATUS = '' AND CLOSED_AT = ''  THEN [PRICE]*[QTY_ADJ] ELSE 0 END AS GROSS_DEMAND_UNFULFILLED
,CASE WHEN DATEDIFF(DAY,CREATED_AT,GETDATE()) > 2 AND FULFILLMENT_STATUS = '' AND CLOSED_AT = ''  THEN [PRICE]*[QTY_ADJ] ELSE 0 END AS GROSS_DEMAND_UNFULFILLED_LATE
,FULFILLMENT_STATUS
,TAX_CODE
,SHIPPING_ADDRESS_NAME
,SHIPPING_FIRST_NAME
,SHIPPING_LAST_NAME
,SHIPPING_COMPANY
,SHIPPING_PHONE
,SHIPPING_ADDRESS_1
,SHIPPING_ADDRESS_2
,SHIPPING_CITY
,SHIPPING_ZIP_CODE
,SHIPPING_PROVINCE
,SHIPPING_PROVINCE_CODE
,SHIPPING_COUNTRY
,SHIPPING_COUNTRY_CODE
,BILLING_ADDRESS_NAME
,BILLING_FIRST_NAME
,BILLING_LAST_NAME
,BILLING_COMPANY
,BILLING_PHONE
,BILLING_ADDRESS_1
,BILLING_ADDRESS_2
,BILLING_CITY
,BILLING_ZIP_CODE
,BILLING_PROVINCE
,BILLING_PROVINCE_CODE
,BILLING_COUNTRY
,BILLING_COUNTRY_CODE

FROM SHOPIFY_UNION WITH (NOLOCK)

LEFT JOIN CAL WITH (NOLOCK)
ON CAL.[DATE] = SHOPIFY_UNION.CREATED_AT

LEFT JOIN #RATE AS RATE_CAD WITH (NOLOCK)
ON RATE_CAD.CURRENCY COLLATE SQL_Latin1_General_CP1_CI_AS = SHOPIFY_UNION.CURRENCY COLLATE SQL_Latin1_General_CP1_CI_AS
AND REPLACE(CREATED_AT, '-','') BETWEEN RATE_CAD.FROM_DATE AND RATE_CAD.TO_DATE
AND RATE_CAD.RATE_TYPE = 'CONVERT TO CAD'