{{ config(materialized='table') }}

with 

final as (

SELECT *
FROM ORDER_FULFILLMENT_CA_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_FULFILLMENT_CA_SK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_FULFILLMENT_US_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_FULFILLMENT_US_SK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_FULFILLMENT_EU_MCK WITH (NOLOCK)

UNION ALL
SELECT *
FROM ORDER_FULFILLMENT_UK_MCK WITH (NOLOCK)

)

SELECT
 CONCAT(REGION,'-',BRAND,'-',[order_id]) AS ID_TABLE
,CONCAT(REGION,'-',BRAND) AS ID_RG_BRAND
,REGION
,BRAND
,BRANCH
,[id]
,[order_id]
,PO
,FULFILLMENT_DATE
,TRACKING_COMPANY
,TRACKING_NUMBER_LINE_ITEMS
,TRACKING_STATUS
,TRACKING_URL
,TRACKING_NUMBER_ORDER_HEADER

FROM SHOPIFY_UNION  WITH (NOLOCK)

)

select * from final