SELECT 
 [date_day]
,[account_id]
,[account_name]
,[campaign_id]
,[campaign_name]
,[ad_set_id]
,[ad_set_name]
,[ad_id]
,[ad_name]
,[clicks]
,[impressions]
,[spend]

FROM [SHOPIFY_PROD].[facebook_ads].[V_META_ADS]