{{ config(materialized='table') }}

with 

final as (

SELECT
 REGION = 'UK'
,BRAND = 'MCK'
,BRANCH = 'N31'
,OD.[order_id]
,OD.[id]
,OD.[product_id]
,OD.[variant_id]
,OH_UK_MCK.PO
,OH_UK_MCK.PRE_ORDER_TAG
,OH_UK_MCK.NEWSTORE_FAILED_TAG
,OH_UK_MCK.RISKIFIED_DECLINED_TAG
,OH_UK_MCK.SFCC_TAG
,OH_UK_MCK.CURRENCY
,OH_UK_MCK.FINANCIAL_STATUS
,OH_UK_MCK.FULFILLMENT_STATUS AS ORDER_STATUS
,OH_UK_MCK.PROCESSED_AT_FULL
,OH_UK_MCK.PROCESSED_AT
,OH_UK_MCK.CREATED_AT_FULL
,OH_UK_MCK.CREATED_AT
,OH_UK_MCK.CANCELLED_AT_FULL
,OH_UK_MCK.CANCELLED_AT
,OH_UK_MCK.CANCEL_REASON
,OH_UK_MCK.CLOSED_AT_FULL
,OH_UK_MCK.CLOSED_AT
,OH_UK_MCK.EMAIL
,OH_UK_MCK.NOTE
,OD.[vendor] AS BRAND_ITEM
,OD.[title] AS STYLE
,OD.[variant_title] AS VARIANT
,OD.[name] AS FULL_NAME
,OD.[sku] AS SKU
,OD.[price] AS PRICE
,OD.[total_discount] AS TOTAL_DISCOUNT
,OD.[quantity] AS QTY
,OD.[pre_tax_price] AS SUBTOTAL
,CASE WHEN OH_UK_MCK.CANCEL_REASON = 'fraud' THEN 0 ELSE OD.[quantity] END AS QTY_ADJ
,CASE WHEN OH_UK_MCK.CANCEL_REASON = 'fraud' THEN 0 ELSE OD.[pre_tax_price] END AS SUBTOTAL_ADJ
,ISNULL(OD.[fulfillment_status],'') AS FULFILLMENT_STATUS
,ISNULL(OD.[tax_code],'') AS TAX_CODE
,OH_UK_MCK.SHIPPING_ADDRESS_NAME
,OH_UK_MCK.SHIPPING_FIRST_NAME
,OH_UK_MCK.SHIPPING_LAST_NAME
,OH_UK_MCK.SHIPPING_COMPANY
,OH_UK_MCK.SHIPPING_PHONE
,OH_UK_MCK.SHIPPING_ADDRESS_1
,OH_UK_MCK.SHIPPING_ADDRESS_2
,OH_UK_MCK.SHIPPING_CITY
,OH_UK_MCK.SHIPPING_ZIP_CODE
,OH_UK_MCK.SHIPPING_PROVINCE
,OH_UK_MCK.SHIPPING_PROVINCE_CODE
,OH_UK_MCK.SHIPPING_COUNTRY
,OH_UK_MCK.SHIPPING_COUNTRY_CODE
,OH_UK_MCK.BILLING_ADDRESS_NAME
,OH_UK_MCK.BILLING_FIRST_NAME
,OH_UK_MCK.BILLING_LAST_NAME
,OH_UK_MCK.BILLING_COMPANY
,OH_UK_MCK.BILLING_PHONE
,OH_UK_MCK.BILLING_ADDRESS_1
,OH_UK_MCK.BILLING_ADDRESS_2
,OH_UK_MCK.BILLING_CITY
,OH_UK_MCK.BILLING_ZIP_CODE
,OH_UK_MCK.BILLING_PROVINCE
,OH_UK_MCK.BILLING_PROVINCE_CODE
,OH_UK_MCK.BILLING_COUNTRY
,OH_UK_MCK.BILLING_COUNTRY_CODE

FROM [SHOPIFY_PROD].[uk_mck].[order_line] AS OD WITH (NOLOCK)

LEFT JOIN OH_UK_MCK WITH (NOLOCK)
ON OH_UK_MCK.[id] = OD.[order_id]

    )

select * from final