# for source packages/pulling from the raw connector data

version: 2

sources:
  - name: nsevent 
    database: "{{ var ('connector_database', target.database) }}"
    schema: "{{ var ('connector_schema', 'nsevent') }}"

    loader: fivetran
    loaded_at_field: _fivetran_synced
      
    freshness:
      warn_after: {count: 72, period: hour}
      error_after: {count: 96, period: hour}

    tables:
    # tables with table and column- level descriptions
      