
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'DBT_APP'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'DBT_APP'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  DBT_APP:
    # Config indicated by + and applies to all files under models/example/
    ads_google:
      +schema: google_ads
      +materialized: table
      +database: SHOPIFY_PROD
    newstore:
      +schema: newstore
      +materialized: table
    sms:
      +schema: sms
      +materialized: view
    m3:
      +schema: dbo
      +materialized: table
      +database: M3RPTDEV
    google_ads_mck:
      +schema: google_ads_mck
      +materialized: view
      +database: SHOPIFY_PROD
    google_ads_sk:
      +schema: google_ads_sk
      +materialized: view
      +database: SHOPIFY_PROD
    facebook_ads:
      +schema: facebook_ads
      +materialized: view
      +database: SHOPIFY_PROD
    google_analytics:
      +schema: google_analytics
      +materialized: view
      +database: SHOPIFY_PROD
    google_analytics_4:
      +schema: google_analytics_4
      +materialized: table
      +database: SHOPIFY_PROD
    loop_ca:
      +schema: loop_ca
      +materialized: table
      +database: SHOPIFY_PROD
    centricplm:
      +schema: centricplm
      +materialized: table
      +database: M3RPTDEV